import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "var(--surface-variant)",
        "outline-variant": "var(--outline-variant)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "secondary": "var(--secondary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "primary": "var(--primary)",
        "surface-bright": "var(--surface-bright)",
        "surface-tint": "var(--surface-tint)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "error-container": "var(--error-container)",
        "primary-container": "var(--primary-container)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-dim": "var(--surface-dim)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "tertiary": "var(--tertiary)",
        "on-surface": "var(--on-surface)",
        "background": "var(--background)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "tertiary-container": "var(--tertiary-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-error-container": "var(--on-error-container)",
        "surface-container-low": "var(--surface-container-low)",
        "surface": "var(--surface)",
        "error": "var(--error)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "secondary-container": "var(--secondary-container)",
        "outline": "var(--outline)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-error": "var(--on-error)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "primary-fixed": "var(--primary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-container-high": "var(--surface-container-high)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "surface-container": "var(--surface-container)",
        "on-background": "var(--on-background)",
        "on-primary": "var(--on-primary)",
        "on-primary-container": "var(--on-primary-container)",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
export default config;
